[tool.black]
line-length=120

[tool.isort]
profile = "black"
skip = [".gitignore", ".venv"]
extend_skip = [".md"]

[tool.pytest.ini_options]
addopts = "-svv --cov=app"
testpaths = [
    "tests",
]
asyncio_default_fixture_loop_scope = "function"
