# This workflow will install uv and run code formatting and linting checks

name: lint-and-format

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: lint and format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: isort
      run: |
        uv run isort app/ --check-only --verbose
        uv run isort tests/ --check-only --verbose

    - name: black
      run: |
        uv run black app/ --check --verbose
        uv run black tests/ --check --verbose

    - name: flake8 .
      run: |
        uv run flake8 app/
        uv run flake8 tests/
