# This workflow will install uv and run code formatting and linting checks

name: lint-and-format

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: lint and format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: isort
      run: |
        uv run isort app/ tests/ --check-only

    - name: black
      run: |
        uv run black app/ tests/ --check

    - name: flake8 .
      run: |
        uv run flake8 app/ tests/

  # https://github.com/marketplace/actions/alls-green#why
  check:  # A check for whether the dependency jobs are all green.
    if: always()
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
