name: Python tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-tests:
    name: Unit Tests - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"

    steps:
      - uses: actions/checkout@v4

      - name: "Install uv and set the python version"
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --dev

      - name: Rename .env.example to .env
        run: mv .env.example .env; ls -alh; pwd

      - name: Run unit tests
        run: uv run pytest tests/